services:
  _defaults:
    autowire: true
    autoconfigure: true

  DoctrineFixtures\DataGenerationBundle\Service\:
    resource: '../../Service'
  DoctrineFixtures\DataGenerationBundle\EventSubscriber\:
    resource: '../../EventSubscriber'
